// Content database for the portfolio. Bilingual EN/UA.
// All sample content is realistic but fictional.

const I18N = {
  en: {
    nav: {
      home: "Home",
      work: "Work Samples",
      workflow: "AI Workflow",
      about: "About",
      contact: "Contact",
      cv: "Download CV",
    },
    hero: {
      eyebrow: "AI-assisted Technical Writer",
      title: "I turn source code into documentation engineers actually read.",
      lede: "I help engineering teams turn source code, APIs, and internal systems into clear, maintainable documentation — using AI for structure and drafting, with every technical claim validated against the code.",
      ctaPrimary: "View Work Samples",
      ctaSecondary: "See AI Workflow",
      meta: [
        { k: "Available", v: "Remote, EU/US" },
        { k: "Engagement", v: "B2B · Vendor · Contract" },
        { k: "Response", v: "Within 24h" },
      ],
    },
    whatIDocument: {
      title: "What I document",
      subtitle: "Five areas where I've shipped production documentation.",
      cards: [
        { num: "01", title: "API Documentation", body: "REST APIs, OpenAPI specs, authentication flows, error catalogs, request/response examples and quickstart tutorials." },
        { num: "02", title: "Codebase Documentation", body: "Architecture notes, module references, configuration, troubleshooting runbooks and onboarding maps for unfamiliar repos." },
        { num: "03", title: "Developer Onboarding", body: "Setup guides, local environment, first-contribution flow, environment variables and a working hello-world in under 30 minutes." },
        { num: "04", title: "Internal Engineering Docs", body: "Runbooks, release process, ADRs (architecture decision records), incident postmortems and a searchable knowledge base." },
        { num: "05", title: "AI-assisted Workflow", body: "Prompt templates, hallucination prevention checklist, validation steps and review processes that scale across writers." },
      ],
    },
    featured: {
      title: "Featured samples",
      subtitle: "Selected documentation projects with input materials, process and outcome.",
      viewAll: "View all samples",
    },
    workflow: {
      title: "AI documentation workflow",
      subtitle: "How I structure work so AI accelerates research and drafting without leaking hallucinations into the final docs.",
      cta: "Read the full workflow",
    },
    tools: {
      title: "Tools I work with",
      groups: [
        { label: "Authoring", items: ["Markdown", "MDX", "AsciiDoc", "VS Code"] },
        { label: "Docs-as-Code", items: ["GitHub", "Jekyll", "GitHub Pages", "Docusaurus", "MkDocs"] },
        { label: "API", items: ["OpenAPI", "Swagger", "Postman", "Insomnia"] },
        { label: "Collaboration", items: ["Confluence", "Jira", "Notion", "Linear"] },
        { label: "AI", items: ["ChatGPT", "Claude", "GitHub Copilot", "Cursor"] },
      ],
    },
    finalCta: {
      title: "Need help turning code into documentation?",
      body: "Available for remote collaboration with engineering teams, startups, agencies and vendor-based partnerships.",
      ctaPrimary: "Contact me",
      ctaSecondary: "Download CV",
    },
    workPage: {
      title: "Work Samples",
      subtitle: "Documentation projects with input materials, process and outcome. Filter by topic.",
      filters: ["All", "API Docs", "Code-to-Docs", "Developer Onboarding", "AI Workflow", "Internal Docs"],
      input: "Input",
      output: "Output",
      view: "View sample",
      github: "GitHub",
    },
    workflowPage: {
      title: "AI-assisted documentation, reviewed like engineering work.",
      lede: "I use AI to accelerate research, structure and drafting. Every technical statement is then validated against source code, product behavior, API responses or SME feedback before it ships.",
      tocTitle: "On this page",
      principles: {
        title: "Operating principles",
        items: [
          { k: "AI drafts. Code decides.", v: "Source code, OpenAPI, server logs and SME interviews are ground truth. AI output is treated as a hypothesis until verified." },
          { k: "Review checklist beats vibes.", v: "Every doc passes a short checklist: claims verified, examples runnable, terms consistent, edge cases mentioned." },
          { k: "Same workflow for repeat work.", v: "Templates and prompts are reusable, so the second API doc costs less than the first." },
        ],
      },
      checklist: {
        title: "Hallucination prevention checklist",
        items: [
          "Every code snippet was copy-pasted from the actual codebase or run locally.",
          "Every API example returns the documented status code and shape.",
          "All endpoints, parameters and types match the OpenAPI source.",
          "All version numbers, package names and CLI flags were confirmed in the repo.",
          "Acronyms are expanded on first use.",
          "Terms match the product UI and the engineering team's vocabulary.",
          "An SME reviewed the doc before publication.",
          "Edge cases and error states are covered.",
        ],
      },
      prompts: {
        title: "Example prompts I use",
      },
    },
    aboutPage: {
      title: "About",
      bio: "I'm a technical writer focused on developer documentation, codebase docs, API docs and AI-assisted documentation workflows. I help engineering teams transform technical context into clear, maintainable documentation.",
      bio2: "I work directly inside repositories, ship documentation through Pull Requests and treat docs as a system: structure, navigation, style, examples, review, maintenance.",
      coreSkillsTitle: "Core skills",
      coreSkills: ["Code-to-docs translation", "API reference & quickstarts", "Information architecture", "Docs-as-Code (Git, Markdown, CI)", "Style guide authoring", "Editorial review", "AI prompt design", "Technical interviewing"],
      experienceTitle: "Experience summary",
      experience: [
        { period: "2024 — Now", role: "AI-assisted Technical Writer", org: "Independent", body: "Documentation contracts for B2B SaaS, fintech and developer-tools companies. API docs, codebase docs, onboarding guides and AI workflow consulting." },
        { period: "2021 — 2024", role: "Senior Technical Writer", org: "Developer-tools startup", body: "Owned the public docs portal, built the docs-as-code pipeline, ran style and review process for 6 contributing engineers." },
        { period: "2019 — 2021", role: "Technical Writer", org: "B2B SaaS", body: "API reference, integration guides, internal runbooks and changelog process." },
      ],
      engagementTitle: "Engagement models",
      engagement: ["Direct B2B contracts", "Vendor / agency partnerships", "Contractor platforms", "Part-time projects", "Documentation audits"],
    },
    contactPage: {
      title: "Let's talk documentation.",
      lede: "Need help turning code, APIs, or engineering knowledge into clear documentation? I'm available for remote technical writing projects, documentation audits, and AI-assisted documentation workflows.",
      formTitle: "Send a brief",
      labels: { name: "Your name", email: "Email", company: "Company (optional)", topic: "Topic", message: "Brief", send: "Send via email" },
      topics: ["API Documentation", "Codebase Documentation", "Developer Onboarding", "Internal Engineering Docs", "AI Documentation Workflow", "Documentation Audit", "Other"],
      directTitle: "Or reach me directly",
      responseNote: "Typically responds within 24 hours, weekdays.",
    },
  },
  ua: {
    nav: {
      home: "Головна",
      work: "Приклади робіт",
      workflow: "AI Workflow",
      about: "Про мене",
      contact: "Контакти",
      cv: "Завантажити CV",
    },
    hero: {
      eyebrow: "Технічний письменник з AI",
      title: "Перетворюю код на документацію, яку інженери справді читають.",
      lede: "Допомагаю інженерним командам перетворювати код, API та внутрішні системи на зрозумілу, підтримувану документацію — використовуючи AI для структури й драфтингу, з обов'язковою перевіркою кожного технічного твердження по коду.",
      ctaPrimary: "Дивитись приклади",
      ctaSecondary: "AI Workflow",
      meta: [
        { k: "Доступний", v: "Remote, EU/US" },
        { k: "Формат", v: "B2B · Vendor · Контракт" },
        { k: "Відповідь", v: "Протягом 24 годин" },
      ],
    },
    whatIDocument: {
      title: "Що я документую",
      subtitle: "П'ять напрямів, де я постачав production-документацію.",
      cards: [
        { num: "01", title: "API-документація", body: "REST API, OpenAPI-специфікації, потоки автентифікації, каталоги помилок, приклади запитів і відповідей, quickstart-туторіали." },
        { num: "02", title: "Документація кодової бази", body: "Архітектурні нотатки, довідник модулів, конфігурація, runbooks для траблшутингу та onboarding-мапи для нових репозиторіїв." },
        { num: "03", title: "Developer Onboarding", body: "Гайди із встановлення, локальне середовище, флоу першого контрибуту, змінні середовища і робочий hello-world менш ніж за 30 хвилин." },
        { num: "04", title: "Внутрішні інженерні docs", body: "Runbooks, release process, ADR (architecture decision records), incident postmortems і пошуковий knowledge base." },
        { num: "05", title: "AI-assisted Workflow", body: "Шаблони промптів, чекліст запобігання галюцинаціям, кроки валідації та процеси review, що масштабуються між авторами." },
      ],
    },
    featured: {
      title: "Обрані приклади",
      subtitle: "Документаційні проєкти з input-матеріалами, процесом і результатом.",
      viewAll: "Усі приклади",
    },
    workflow: {
      title: "AI documentation workflow",
      subtitle: "Як я структурую роботу, щоб AI прискорював дослідження й драфтинг, але галюцинації не потрапляли у фінальні docs.",
      cta: "Повний опис workflow",
    },
    tools: {
      title: "Інструменти, з якими працюю",
      groups: [
        { label: "Authoring", items: ["Markdown", "MDX", "AsciiDoc", "VS Code"] },
        { label: "Docs-as-Code", items: ["GitHub", "Jekyll", "GitHub Pages", "Docusaurus", "MkDocs"] },
        { label: "API", items: ["OpenAPI", "Swagger", "Postman", "Insomnia"] },
        { label: "Колаборація", items: ["Confluence", "Jira", "Notion", "Linear"] },
        { label: "AI", items: ["ChatGPT", "Claude", "GitHub Copilot", "Cursor"] },
      ],
    },
    finalCta: {
      title: "Потрібна допомога з перетворенням коду на документацію?",
      body: "Доступний для remote-співпраці з інженерними командами, стартапами, агенціями та vendor-партнерствами.",
      ctaPrimary: "Написати",
      ctaSecondary: "Завантажити CV",
    },
    workPage: {
      title: "Приклади робіт",
      subtitle: "Документаційні проєкти з input-матеріалами, процесом і результатом. Фільтруйте за темою.",
      filters: ["Усі", "API Docs", "Code-to-Docs", "Developer Onboarding", "AI Workflow", "Internal Docs"],
      input: "Вхід",
      output: "Вихід",
      view: "Дивитись приклад",
      github: "GitHub",
    },
    workflowPage: {
      title: "AI-документація, відрев'ювана як інженерна робота.",
      lede: "Я використовую AI для прискорення дослідження, структурування і драфтингу. Кожне технічне твердження потім валідовано по коду, поведінці продукту, API-відповідях або SME-фідбеку перед публікацією.",
      tocTitle: "На цій сторінці",
      principles: {
        title: "Робочі принципи",
        items: [
          { k: "AI пише драфт. Код вирішує.", v: "Source code, OpenAPI, server logs та SME-інтерв'ю — це ground truth. Output AI трактується як гіпотеза до моменту верифікації." },
          { k: "Чекліст замість 'на око'.", v: "Кожен документ проходить короткий чекліст: твердження верифіковано, приклади запускаються, термінологія узгоджена, edge cases згадано." },
          { k: "Один workflow для повторної роботи.", v: "Шаблони й промпти багаторазові, тож друга API-документація коштує менше, ніж перша." },
        ],
      },
      checklist: {
        title: "Чекліст запобігання галюцинаціям",
        items: [
          "Кожен code-сніпет скопійовано з реальної кодової бази або запущено локально.",
          "Кожен API-приклад повертає задокументований статус і shape.",
          "Усі endpoints, параметри і типи відповідають OpenAPI-джерелу.",
          "Усі номери версій, назви пакетів і CLI-прапорці підтверджено у репозиторії.",
          "Акроніми розкрито при першому використанні.",
          "Терміни відповідають UI продукту і словнику інженерної команди.",
          "SME переглянув документ перед публікацією.",
          "Edge cases і error states покрито.",
        ],
      },
      prompts: {
        title: "Приклади промптів",
      },
    },
    aboutPage: {
      title: "Про мене",
      bio: "Я — технічний письменник із фокусом на developer documentation, codebase docs, API docs та AI-assisted documentation workflows. Допомагаю інженерним командам перетворювати технічний контекст на зрозумілу, підтримувану документацію.",
      bio2: "Працюю безпосередньо всередині репозиторіїв, постачаю документацію через Pull Requests і ставлюся до docs як до системи: структура, навігація, стиль, приклади, review, підтримка.",
      coreSkillsTitle: "Ключові навички",
      coreSkills: ["Переклад коду в docs", "API reference і quickstarts", "Інформаційна архітектура", "Docs-as-Code (Git, Markdown, CI)", "Розробка style guide", "Редакційний review", "AI prompt design", "Технічне інтерв'ювання"],
      experienceTitle: "Досвід",
      experience: [
        { period: "2024 — зараз", role: "AI-assisted Technical Writer", org: "Незалежний", body: "Документаційні контракти для B2B SaaS, fintech і developer-tools компаній. API docs, codebase docs, onboarding-гайди й AI workflow консалтинг." },
        { period: "2021 — 2024", role: "Senior Technical Writer", org: "Developer-tools стартап", body: "Володів публічним docs-порталом, побудував docs-as-code pipeline, керував style і review process для 6 контрибуторів-інженерів." },
        { period: "2019 — 2021", role: "Technical Writer", org: "B2B SaaS", body: "API reference, integration guides, internal runbooks і changelog process." },
      ],
      engagementTitle: "Формати співпраці",
      engagement: ["Прямі B2B-контракти", "Vendor / agency партнерства", "Платформи для контракторів", "Part-time проєкти", "Аудити документації"],
    },
    contactPage: {
      title: "Поговорімо про документацію.",
      lede: "Потрібна допомога з перетворенням коду, API чи інженерних знань на зрозумілу документацію? Доступний для remote technical writing проєктів, аудитів документації та AI workflow.",
      formTitle: "Надіслати бриф",
      labels: { name: "Ім'я", email: "Email", company: "Компанія (опційно)", topic: "Тема", message: "Бриф", send: "Надіслати email" },
      topics: ["API-документація", "Codebase Documentation", "Developer Onboarding", "Внутрішні інженерні docs", "AI Documentation Workflow", "Аудит документації", "Інше"],
      directTitle: "Або напряму",
      responseNote: "Зазвичай відповідаю протягом 24 годин у будні.",
    },
  },
};

const SAMPLES = [
  {
    id: "rest-api-docs",
    title: { en: "REST API Documentation Sample", ua: "Приклад документації REST API" },
    summary: { en: "Endpoint reference, auth guide, request/response examples, error handling and quickstart flow for a task management API.", ua: "Reference endpoints, гайд автентифікації, приклади запитів/відповідей, обробка помилок і quickstart для task management API." },
    tags: ["API Docs", "OpenAPI", "REST"],
    category: "API Docs",
    tools: ["Markdown", "OpenAPI", "GitHub", "Postman"],
    input: { en: ["OpenAPI specification", "README", "Source code", "Engineer interviews"], ua: ["OpenAPI-специфікація", "README", "Source code", "Інтерв'ю з інженерами"] },
    output: { en: ["API overview", "Authentication guide", "Endpoint reference", "Error catalog", "Quickstart"], ua: ["Огляд API", "Гайд автентифікації", "Reference endpoints", "Каталог помилок", "Quickstart"] },
    featured: true,
    order: 1,
    accent: "cyan",
  },
  {
    id: "code-to-docs",
    title: { en: "Code-to-Docs Sample", ua: "Приклад Code-to-Docs" },
    summary: { en: "Module-by-module documentation pulled from a TypeScript backend: architecture map, configuration reference, troubleshooting.", ua: "Модульна документація для TypeScript-бекенду: карта архітектури, reference конфігурації, troubleshooting." },
    tags: ["Code-to-Docs", "Codebase", "TypeScript"],
    category: "Code-to-Docs",
    tools: ["Markdown", "GitHub", "Mermaid", "VS Code"],
    input: { en: ["TypeScript source", "Existing inline comments", "Issue tickets", "PR history"], ua: ["TypeScript source", "Існуючі inline-коментарі", "Issue tickets", "PR-історія"] },
    output: { en: ["Architecture overview", "Module reference", "Config reference", "Troubleshooting runbook"], ua: ["Огляд архітектури", "Reference модулів", "Reference конфігурації", "Runbook для troubleshooting"] },
    featured: true,
    order: 2,
    accent: "violet",
  },
  {
    id: "developer-onboarding",
    title: { en: "Developer Onboarding Guide", ua: "Гайд Developer Onboarding" },
    summary: { en: "First 30 minutes for new engineers: env setup, repo tour, hello-world commit, where to ask, who owns what.", ua: "Перші 30 хвилин для нового інженера: налаштування середовища, тур репозиторієм, hello-world commit, кому ставити питання." },
    tags: ["Developer Onboarding", "Internal Docs"],
    category: "Developer Onboarding",
    tools: ["Markdown", "GitHub", "Make", "Docker"],
    input: { en: ["Existing setup README", "New-hire interviews", "Slack threads", "Internal wiki"], ua: ["Існуючий setup README", "Інтерв'ю з новачками", "Slack-треди", "Внутрішня вікі"] },
    output: { en: ["30-minute setup path", "Repo tour", "First-PR checklist", "Ownership map"], ua: ["30-хвилинний setup path", "Тур репозиторієм", "Чекліст першого PR", "Карта ownership"] },
    featured: true,
    order: 3,
    accent: "emerald",
  },
  {
    id: "ai-workflow-case",
    title: { en: "AI Workflow Case Study", ua: "Кейс AI Workflow" },
    summary: { en: "How a 4-engineer team scaled documentation 3× without hiring, using prompt templates, validation steps and a review checklist.", ua: "Як команда з 4 інженерів масштабувала документацію в 3 рази без найму — через шаблони промптів, кроки валідації й review-чекліст." },
    tags: ["AI Workflow", "Process", "Templates"],
    category: "AI Workflow",
    tools: ["Claude", "ChatGPT", "GitHub", "Notion"],
    input: { en: ["Existing docs", "Team interviews", "Style guide", "Engineering OKRs"], ua: ["Існуючі docs", "Інтерв'ю команди", "Style guide", "Інженерні OKR"] },
    output: { en: ["Prompt library", "Validation checklist", "Review process", "Templates"], ua: ["Бібліотека промптів", "Чекліст валідації", "Review-процес", "Шаблони"] },
    featured: true,
    order: 4,
    accent: "amber",
  },
  {
    id: "edge-veda-code-to-docs",
    title: { en: "Edge-Veda Code-to-Docs Case", ua: "Кейс Edge-Veda Code-to-Docs" },
    summary: { en: "Documentation plan and Getting Started draft for an open-source on-device AI runtime for Flutter — repository review, public API inventory and a PR-ready first guide.", ua: "План документації та чернетка Getting Started для open-source on-device AI runtime для Flutter — рев'ю репозиторію, інвентаризація публічного API і перший гайд, готовий для PR." },
    tags: ["Code-to-Docs", "AI SDK", "Flutter", "Docs-as-Code", "Open Source"],
    category: "Code-to-Docs",
    tools: ["GitHub", "Markdown", "Dart", "ChatGPT", "dart doc"],
    input: { en: ["GitHub repository", "README and quickstart", "flutter/lib/ source", "flutter/example/ app", "Documentation issue", "AI-assisted analysis prompts"], ua: ["GitHub-репозиторій", "README і quickstart", "Сорс flutter/lib/", "Приклад flutter/example/", "Issue про документацію", "AI-промпти для аналізу"] },
    output: { en: ["Documentation gap analysis", "Public API inventory", "Getting Started draft", "Usage example plan", "Validation checklist", "PR description"], ua: ["Аналіз прогалин у docs", "Інвентаризація публічного API", "Чернетка Getting Started", "План прикладів використання", "Чекліст валідації", "Опис PR"] },
    status: { en: "Draft / Open-source contribution in preparation", ua: "Чернетка / Open-source контрибут у підготовці" },
    featured: true,
    order: 5,
    accent: "emerald",
  },
  {
    id: "internal-runbooks",
    title: { en: "Internal Engineering Runbooks", ua: "Внутрішні інженерні runbooks" },
    summary: { en: "Incident response, deploy rollbacks and on-call procedures structured for fast scanning under pressure.", ua: "Incident response, відкат деплоїв і on-call процедури, структуровані для швидкого скану під тиском." },
    tags: ["Internal Docs", "Runbooks"],
    category: "Internal Docs",
    tools: ["Markdown", "Confluence", "PagerDuty"],
    input: { en: ["Incident postmortems", "On-call interviews", "Slack incident channels"], ua: ["Incident postmortems", "Інтерв'ю on-call", "Slack incident-канали"] },
    output: { en: ["Incident runbooks", "Rollback procedures", "On-call playbook"], ua: ["Incident runbooks", "Процедури rollback", "On-call playbook"] },
    featured: false,
    order: 6,
    accent: "cyan",
  },
  {
    id: "docs-as-code-setup",
    title: { en: "Docs-as-Code Setup", ua: "Налаштування Docs-as-Code" },
    summary: { en: "Repository structure, branch policy, lint rules, preview builds and PR review process for a new docs repo.", ua: "Структура репозиторію, branch-політика, lint-правила, preview-білди й PR-review для нового docs-репо." },
    tags: ["Code-to-Docs", "Internal Docs"],
    category: "Code-to-Docs",
    tools: ["GitHub Actions", "Vale", "Markdownlint", "Jekyll"],
    input: { en: ["Existing scattered docs", "Style guide", "CI requirements"], ua: ["Розкидані docs", "Style guide", "CI-вимоги"] },
    output: { en: ["Monorepo docs structure", "CI workflow", "PR template", "Style linting"], ua: ["Структура monorepo docs", "CI workflow", "PR-шаблон", "Style linting"] },
    featured: false,
    order: 7,
    accent: "violet",
  },
];

const API_DOCS = [
  {
    id: "edgeveda-init",
    parentSample: "rest-api-docs",
    title: { en: "EdgeVeda.init()", ua: "EdgeVeda.init()" },
    description: {
      en: "Initializes the Edge Veda runtime configuration and verifies that the selected on-device model can be loaded.",
      ua: "Ініціалізує конфігурацію Edge Veda runtime і перевіряє, що вибрану on-device модель можна завантажити.",
    },
    tags: ["Dart SDK", "On-device AI", "Runtime"],
    method: "init()",
    className: "EdgeVeda",
    stability: "Stable",
    since: "2.5.0",
    category: "Core inference",
  },
  {
    id: "edgeveda-generate",
    parentSample: "rest-api-docs",
    title: { en: "EdgeVeda.generate()", ua: "EdgeVeda.generate()" },
    description: {
      en: "Generates a complete text response from a prompt by collecting tokens from the persistent streaming worker.",
      ua: "Генерує повну текстову відповідь із prompt, збираючи токени з persistent streaming worker.",
    },
    tags: ["Dart SDK", "On-device AI", "Text Generation"],
    method: "generate()",
    className: "EdgeVeda",
    stability: "Stable",
    since: "2.5.0",
    category: "Core inference",
  },
  {
    id: "edgeveda-generate-stream",
    parentSample: "rest-api-docs",
    title: { en: "EdgeVeda.generateStream()", ua: "EdgeVeda.generateStream()" },
    description: {
      en: "Generates text as a stream of token chunks for progressive, responsive on-device AI experiences.",
      ua: "Генерує текст як stream token chunks для responsive on-device AI experiences.",
    },
    tags: ["Dart SDK", "On-device AI", "Streaming"],
    method: "generateStream()",
    className: "EdgeVeda",
    stability: "Stable",
    since: "2.5.0",
    category: "Core inference",
  },
  {
    id: "edgeveda-describe-image",
    parentSample: "rest-api-docs",
    title: { en: "EdgeVeda.describeImage()", ua: "EdgeVeda.describeImage()" },
    description: {
      en: "Generates a text description of an RGB image using the initialized vision-language model.",
      ua: "Генерує text description для RGB image за допомогою ініціалізованої vision-language model.",
    },
    tags: ["Dart SDK", "On-device AI", "Vision"],
    method: "describeImage()",
    className: "EdgeVeda",
    stability: "Stable",
    since: "2.5.0",
    category: "Vision",
  },
  {
    id: "edgeveda-embed",
    parentSample: "rest-api-docs",
    title: { en: "EdgeVeda.embed()", ua: "EdgeVeda.embed()" },
    description: {
      en: "Computes a text embedding vector for one input string using the initialized local embedding model.",
      ua: "Обчислює text embedding vector для одного input string за допомогою ініціалізованої локальної embedding model.",
    },
    tags: ["Dart SDK", "On-device AI", "Embeddings"],
    method: "embed()",
    className: "EdgeVeda",
    stability: "Stable",
    since: "2.5.0",
    category: "Embeddings / RAG",
  },
  {
    id: "edgeveda-embed-batch",
    parentSample: "rest-api-docs",
    title: { en: "EdgeVeda.embedBatch()", ua: "EdgeVeda.embedBatch()" },
    description: {
      en: "Computes embedding vectors for multiple text strings in one model load/unload cycle.",
      ua: "Обчислює embedding vectors для кількох text strings за один model load/unload cycle.",
    },
    tags: ["Dart SDK", "On-device AI", "Embeddings"],
    method: "embedBatch()",
    className: "EdgeVeda",
    stability: "Stable",
    since: "2.5.0",
    category: "Embeddings / RAG",
  },
];

window.I18N = I18N;
window.SAMPLES = SAMPLES;
window.API_DOCS = API_DOCS;
